---
config:
    look: neo
    layout: elk
    theme: mc
---
flowchart TD
    subgraph gateway["Web Layer (Gateway)"]
        FE["frontend (NginX)"]
    end

    subgraph API["API"]
        BE["backend (FastAPI + Celery master)"]
    end

    subgraph Workers["Workers"]
        CPU["worker-cpu (Celery worker)"]
        GPU["worker-gpu (Celery worker)"]
    end

    subgraph Queue["Queue"]
        REDIS["redis"]
    end

    subgraph Monitoring["Monitoring"]
        FLOWER["flower"]
        CELX["celery-exporter"]
        PROM["prometheus"]
        GRAFANA["grafana"]
    end

    subgraph initscripts["Init Scripts for Monitoring"]
        RMF["remove-monitoring-flag"]
        MONF["monitoring-flag"]
    end

    FE --> BE & RMF & GRAFANA & FLOWER
    BE --> REDIS
    CPU --> REDIS & BE
    GPU --> REDIS & BE
    FLOWER --> REDIS & BE
    CELX --> PROM & BE
    PROM --> GRAFANA
    MONF --> RMF

    FLOWER:::optional
    CELX:::optional
    PROM:::optional
    GRAFANA:::optional
    MONF:::optional

    classDef optional fill:#95e6ff,stroke:#333,stroke-width:1px,color:#333
